#Processamento Digital de Imagens - NumPY

In [1]:
pip install numpy

In [13]:
import numpy as np

a = np.matrix([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])
print(a)

print("------------------------------")

print(type(a))

print("------------------------------")

print("Linha 0: a[0]")
print(a[0])
print("Linha 0: a[0,:]")
print(a[0,:])

print("------------------------------")

print("Coluna 2: a[:,2]")
print(a[:,2])

print("------------------------------")

print("Pegando os pares de cada linha: a[:,1:4:2]")
print(a[:,1:4:2])

print("------------------------------")

print("Matrix com linhas reversas: a[::-1, :]")
print(a[::-1, :])
print("Matrix com colunas reversas: a[:, ::-1]")
print(a[:,::-1])
print("Matrix com linhas e colunas reversas: a[::-1, ::-1]")
print(a[::-1,::-1])

print("------------------------------")

print("Matrix de zeros: ")
print(np.zeros((3,4)))
print("Matrix de uns:")
print(np.ones((4,3)))

print("------------------------------")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
<class 'numpy.matrix'>
------------------------------
Linha 0: a[0]
[[1 2 3 4]]
Linha 0: a[0,:]
[[1 2 3 4]]
------------------------------
Coluna 2: a[:,2]
[[ 3]
 [ 7]
 [11]]
------------------------------
Pegando os pares de cada linha: a[:,1:4:2]
[[ 2  4]
 [ 6  8]
 [10 12]]
------------------------------
Matrix com linhas reversas: a[::-1, :]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Matrix com colunas reversas: a[:, ::-1]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Matrix com linhas e colunas reversas: a[::-1, ::-1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
------------------------------
Matrix de zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix de uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
import numpy.random as npr

print("Primeira aleatória:")
n1 = np.matrix(npr.randint(1,5,(3,4)))
print(n1)

print("Segunda aleatória:")
n2 = np.matrix(npr.randint(1,5,(3,4)))
print(n2)

print("----------------------------")

a = np.matrix(npr.randint(2,6, (3,3)))
b = a

print("Matrix A:")
print(a)
print("Matrix B apontando para A:")
print(b)

print("----------------------------")

a *= 2

print("Matrix A multiplicado por 2:")
print(a)
print("Matrix B apontando para A:")
print(b)

print("----------------------------")

print("Matrix c recortada:")
c = a[0:2, :]
print(c)

a[0,1] = 1
print("Como é referência de objeto, A e B são atualizadas em [0,1]")
print("Matrix A: ")
print(a)
print("Matrix B: ")
print(b)
print("Matrix C: ")
print(c)

print("----------------------------")

d = np.matrix(c)

c[0,0] = 3

print("Como D cria matrix a partir de D, ela não é afetada pela atualização. Apenas A e C que apontam pro mesmo objeto")
print("Matrix A:")
print(a)
print("Matrix C:")
print(c)
print("Matrix D:")
print(d)


Primeira aleatória:
[[4 1 1 1]
 [2 3 3 2]
 [2 2 4 3]]
Segunda aleatória:
[[3 1 1 2]
 [1 2 2 1]
 [4 3 2 3]]
----------------------------
Matrix A:
[[4 4 2]
 [3 4 3]
 [4 5 4]]
Matrix B apontando para A:
[[4 4 2]
 [3 4 3]
 [4 5 4]]
----------------------------
Matrix A multiplicado por 2:
[[ 8  8  4]
 [ 6  8  6]
 [ 8 10  8]]
Matrix B apontando para A:
[[ 8  8  4]
 [ 6  8  6]
 [ 8 10  8]]
----------------------------
Matrix c recortada:
[[8 8 4]
 [6 8 6]]
Como é referência de objeto, A e B são atualizadas em [0,1]
Matrix A: 
[[ 8  1  4]
 [ 6  8  6]
 [ 8 10  8]]
Matrix B: 
[[ 8  1  4]
 [ 6  8  6]
 [ 8 10  8]]
Matrix C: 
[[8 1 4]
 [6 8 6]]
----------------------------
Matrix A:
[[ 3  1  4]
 [ 6  8  6]
 [ 8 10  8]]
Matrix C:
[[3 1 4]
 [6 8 6]]
Matrix D:
[[8 1 4]
 [6 8 6]]


In [42]:
z = np.matrix(npr.randint(1, 5, (3,4)))
x = np.matrix(npr.randint(1,5, (2,5)))

print(" matrix Z:")
print(z)
print(" matriz X:")
print(x)


print("-----------------------")

print("multiplicando matrizes de dimensões distintas: [3,4] * [2,5]")
# y = z * x
# print(y)
print("dá erro, mostrando que a multiplicação de matrix segue a matemática [n,m] * [x,z] onde m == x")

x = np.matrix(npr.randint(1,5, (4,1)))
y = z * x

print("multiplicando matrizes: [3,4] * [4,1] = [3,1]")
print(y)

print("transposta de Y:")
y = np.transpose(y)
print(y)

print("-------------------------")
k = np.matrix([ [1,2,3], [0,1,4], [0,0,1] ])
print("matrix k: ")
print(k)
print("inversa:")
k **= -1
print(k)
print("traço (soma dos elementos da diagonal principal): ")
k = np.trace(k)
print(k)

print("-------------------------")

p = np.matrix([ [1,2,3], [0,1,4], [0,0,1] ])
print ("determinante:")
p = np.linalg.det(p)
print(p)



 matrix Z:
[[1 3 1 3]
 [3 2 1 1]
 [1 3 2 4]]
 matriz X:
[[2 3 1 4 1]
 [1 4 3 3 1]]
-----------------------
multiplicando matrizes de dimensões distintas: [3,4] * [2,5]
dá erro, mostrando que a multiplicação de matrix segue a matemática [n,m] * [x,z] onde m == x
multiplicando matrizes: [3,4] * [4,1] = [3,1]
[[22]
 [22]
 [28]]
transposta de Y:
[[22 22 28]]
-------------------------
matrix k: 
[[1 2 3]
 [0 1 4]
 [0 0 1]]
inversa:
[[ 1 -2  5]
 [ 0  1 -4]
 [ 0  0  1]]
traço (soma dos elementos da diagonal principal): 
3
-------------------------
determinante:
1.0


TypeError: hstack() takes 1 positional argument but 2 were given